name: Build & Push Client Image

on:
  push:
    branches: [main]
    paths:
      - client/**
      - .github/workflows/client-docker.yml
  workflow_dispatch:

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push client image
        working-directory: client
        run: |
          SHORT_SHA="${GITHUB_SHA::7}"
          docker build -f Dockerfile -t udiecynthia/ceebank:client-dev .
          docker tag udiecynthia/ceebank:client-dev udiecynthia/ceebank:client-${SHORT_SHA}
          docker push udiecynthia/ceebank:client-dev
          docker push udiecynthia/ceebank:client-${SHORT_SHA}

